### ISSUE TITLE
Run rubocop ignoring rubocop TODO

### ISSUE THREAD

**Issue by dgmora** [rubocop/rubocop#10294]
## Is your feature request related to a problem? Please describe.

I would like to be able to run rubocop ignoring `.rubocop_todo.yml`.I use rubocop with my editor as linter and formatter. Even with the TODO, I'd like that the editor tells me about all the issues that rubocop detects, so I can them and fix them bit by bit. But since the TODO is included in the config all these don't get shown by rubocop. I've been looking through the rubocop options but didn't find any that could help with that.

## Describe the solution you'd like

A new option that allows you to ignore the todo could be one way. But whatever is easier and allows me to run rubocop and see the offenses ignoring the rubocop todo.

## Describe alternatives you've considered

What has worked but isn't very optimal is to copy paste `.rubocop.yml` into another file and remove the `inherit_from: rubocop_todo.yml`. Then I run rubocop with `-c other_rubocop.yml`. The project is not only mine, so I don't want to disrupt other people.

**Comment by olliebennett** [comment]
It seems that you could achieve your desired workflow of fixing things one-by-one by actually utilising the todo file instead of ignoring it? My (similar) workflow is;

- Regenerate the TODO list with `bundle exec rubocop --auto-gen-config`
  - I sometimes add `--exclude-limit 500` which writes out a list of all the violating files, allowing you to tackle individual files instead of disabling a whole rule when there are many violating files.
- Commit this updated file (it's fine to share with your team and won't disrupt them)
- Delete one of the rules in the TODO file that you'd like to tackle.
- Re-run `bundle exec rubocop` (with `-A` if you want to auto-correct anything that can be corrected).
- Fix all the issues
- Commit the fixes and the updated TODO file.
- Pick another rule from the TODO file to tackle and repeat!

Is there something with your process that still needs you to bypass the TODO file? And - if you do need to ignore the TODO file - can you just comment out the `inherit_from: .rubocop_todo.yml` line but not commit that change?

**Comment by dgmora** [comment]
I didn't think about using `<% %>`, that's quite a useful trick! Rather than implementing a feature, maybe it'd be nice to mention this in some part of the documentation?

The other workflow isn't going to work with a large codebase, since it's lots of commits and it still changes many files with all that this implies

**Comment by olliebennett** [comment]
Hey, great - glad it helps!

Perhaps this issue itself is sufficient to catch anyone searching for the same solution. I have no strong feelings about adding it to the docs (it still seems a pretty niche requirement to me so not sure where it'd fit in the docs).

As for the other workflow, I see where you're coming from. It does work well on our (pretty large) codebase; rather than changing lots of files, we just pick a single cop or even single file violating that cop (if using a high `--exclude-limit`) and address that in isolation. Totally agree it's important to avoid huge changesets. :)
