### ISSUE TITLE
Cop idea: Replace `ENV['HOME']` with `Dir.home`

### ISSUE THREAD

**Issue by ShockwaveNN** [rubocop/rubocop#10568]
## Is your feature request related to a problem? Please describe.

While fixing issues from latest rubocop update with `Style/FetchEnvVar` cop I found a lot of placed in my code where construction like this used:

```ruby
File.read("#{ENV['HOME']}/foo.file"
```
I got two problems:

1. Autofix from `Style/FetchEnvVar` advice to use
    ```ruby
    File.read("#{ENV.fetch('HOME'), nil]}/foo.file"
    ```
    Which seem rather lengthy for me and do not solve any real problems
2. Not sure that my original code ever worked on `Windows` system (but cannot check it)

## Describe the solution you'd like

Cop that replace all `ENV['HOME']` to `Dir.home` wich will be pure ruby solution to get home dir
But maybe there is some downside in this, but I'm not aware of such

**Comment by rubyFeedback** [comment]
I believe Dir.home may be the better alternative these days. I don't recall since when it was available, but I remember in the very old days we primarily used ENV['HOME']. Dir.home is probably a tiny bit easier to type too - not that it makes a huge difference. But I think if we have not forgotten about some use case then this proposal is probably useful. That is of course only my personal opinion.
