### ISSUE TITLE
 Parser::Source::TreeRewriter detected clobbering during Style/RedundantBegin autocorrect

### ISSUE THREAD

**Issue by bquorning** [rubocop/rubocop#10631]
## Steps to reproduce the problem

When running `rubocop --only=Style/RedundantBegin,Layout/BeginEndAlignment -d -a test.rb` against a file test.rb with the following contents:

```rb
@foo ||= begin
  @bar ||= begin
    baz
  end
end
```

I get (among other things) this output:

```
Inspecting 1 file
Scanning /Users/bquorning/Code/rubocop/rubocop/test.rb
An error occurred while Style/RedundantBegin cop was inspecting /Users/[…]/test.rb:2:11.
Parser::Source::TreeRewriter detected clobbering
```

## RuboCop version

```
$ rubocop -V
1.29.1 (using Parser 3.1.2.0, rubocop-ast 1.17.0, running on ruby 2.7.6 x86_64-darwin20)
  - rubocop-performance 1.13.2
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.10.0
```

**Comment by dvandersluis** [comment]
This actually raises a clobbering error with only `Style/RedundantBegin` too. Because the cop is fixing layout as well, the same range gets changed by the autocorrection for both nodes.

I tried changing autocorrection for `Style/RedundantBegin` to just remove the `begin` and `end` keywords which prevents the clobbering error; however, when run on the sample code, we get a clobbering error from `Layout/RedundantLineBreak` instead.

The clobbering error is of the `swallowed_insertions_conflict` type. I tried using `autocorrect_incompatible_with` but it does not help.
