### ISSUE TITLE
Can we configure Layout/EmptyLines offset?

### ISSUE THREAD

**Issue by zzak** [rubocop/rubocop#11774]
Looking at the docs, it seems there is a `LINE_OFFSET` for 2 lines:
https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/EmptyLines

Having started rails/rails#47854 we realized some of the extra carriage returns were intentional for grouping methods, so a more reasonable assumption might be no more than 3 empty lines 🤔

**Comment by koic** [comment]
According to the comment below, the blank line style used in Rails seems to come from Basecamp:
https://github.com/rails/rails/pull/40193#issuecomment-688581065

But I'm not sure about the Basecamp style is common. And I'm also wondering if the cop should provide a configuration for that. Because the cop doesn't understand the difference in user intent between one blank line and two blank lines. Therefore, even if there are two blank lines when there should be one blank line, it will not be detected.

**Comment by zzak** [comment]
Can the offset be 3, for example? We can then say "no more than 3 consecutive blank lines"?

**Comment by bbatsov** [comment]
We can do it, but this might result in more internal inconsistencies - e.g. someone might put 1 or 2 blank lines instead of 3 and obviously that'd be fine by the cop. I guess I have the same concern as @koic - this config option would solve one problem, but replace it with another one.
