### ISSUE TITLE
Implement support for storing a project-specific config file under .config

### ISSUE THREAD

**Issue by bbatsov** [rubocop/rubocop#12699]
## Is your feature request related to a problem? Please describe.

https://dot-config.github.io/ is an initiative to establish a common location for project-specific configuration files, that aims to declutter the root project folder. I think it'd be nice for RuboCop to support this location. 

## Describe the solution you'd like

Basically we should support `project/.config/.rubocop.yml` as an option for storing project-level RuboCop configuration. So, when RuboCop is started it should check for configuration in the current folder and in `.config` (if present).

**Comment by jasonkarns** [comment]
Question: is there a reason we couldn't use `config/` instead of `.config/`? A good chunk of rubocop users (probably a majority?) are in Rails or Hanami applications where `config/` already exists.

It seems a bit redundant, if not confusing, to have both .config/ and config/ directories side by side?

**Comment by bbatsov** [comment]
While you're probably right (that most Ruby devs are Rails devs), I didn't want to tie ourselves to another particular framework - `.config` is an industry standard. I'm not fundamentally opposed to adding special support for `config`, but I've always felt that's mostly for the application related configuration and not for development tools.
