### ISSUE TITLE
Style/SuperArguments is probably not safe to autocorrect

### ISSUE THREAD

**Issue by tagliala** [rubocop/rubocop#12926]
## Expected behavior

Safe autofix of `Style/SuperArguments` offenses does not break CI

## Actual behavior

Safe autofix breaks CI

## Steps to reproduce the problem

https://github.com/ifad/chronomodel/actions/runs/9206966951/job/25325982139?pr=294#step:6:1076

If we autofix

https://github.com/ifad/chronomodel/blob/804afe24cc5cbf049822e56076c81e4614ec3497/lib/chrono_model/adapter/migrations.rb#L83

then

```
rspec ./spec/chrono_model/adapter/migrations_spec.rb:125
```

fails

```
     Failure/Error: super
     
     LocalJumpError:
       no block given (yield)
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
$ rubocop -V
1.64.0 (using Parser 3.3.1.0, rubocop-ast 1.31.3, running on ruby 3.3.1) [x86_64-darwin23]
  - rubocop-packaging 0.5.2
  - rubocop-performance 1.21.0
  - rubocop-rails 2.25.0
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.29.2
```

**Comment by Earlopain** [comment]
The problem seems to be the assigning of the block which causes it to no longer be passed along.

I specifically tested this with args and kwargs and that worked fine but didn't check out blocks. I would expect this to print `b` 4 times:

```rb
class A
  def positional_arg(a)
    puts a
  end

  def block_arg(&block)
    yield
  end
end

class B < A
  def positional_arg(a = nil)
    a = 'b'
    super
  end

  def block_arg(&block)
    block = proc { puts 'b' }
    super
  end
end

B.new.positional_arg('a')
B.new.positional_arg
B.new.block_arg { puts 'a' }
B.new.block_arg

```

But the output is `b` `b` `a` and `LocalJumpError`. Ruby block handling is weird already and this doesn't make it easier. I'm almost tempted to call this a Ruby bug, if someone has a link to docs for this I would appreciate that. Assigning to the block variable doesn't pass the new one along to super, unless referenced explicitly.

In the meanwhile I'll see about supressing offenses if the block gets reassigned.
