### ISSUE TITLE
Style/TrailingCommaInArrayLiteral and Style/TrailingCommaInHashLiteral use comma by default

### ISSUE THREAD

**Issue by januszm** [rubocop/rubocop#12934]
## Is your feature request related to a problem? Please describe.

Using trailing commas in Array or Hash literals is a convention that helps to avoid spurious differences in version control systems, such as Git. If a new item is added to an Array or Hash literal without trailing commas, this is seen in Git as a change in 2 lines (comma added after the last item, and a new item). This only makes code reviews harder and is a common source of conflicts.

## Describe the solution you'd like

Use `comma` as the new default setting.

**Comment by koic** [comment]
This topic, much like the recurring debates over single versus double quotes in strings, presents opposing viewpoints no matter what the default setting is. Changing the default would simply lead to objections from the other side. Since RuboCop adheres to the Ruby Style Guide, the current default will be maintained. For further information, reference can be made to the following section of the Ruby Style Guide: [No Trailing Params Comma](https://rubystyle.guide/#no-trailing-params-comma). Thank you.
