### ISSUE TITLE
Naming/AccessorMethodName could be more tunable

### ISSUE THREAD

**Issue by akimd** [rubocop/rubocop#13150]
Hi!

## Is your feature request related to a problem? Please describe.

We have a method named `get_min!`.  It has a bang because it's not just an accessor: it has side-effects (and does return a result).

I think that Naming/AccessorMethodName should not fire in this case (names ending with a bang).

We also have other `get_foo` methods, where we use `get_` as a hint that they are costly.  They are not just as cheap as accessors.  It would be nice if Naming/AccessorMethodName had some `AllowedMethods` or `AllowedNames` support for such cases.

## Describe alternatives you've considered

Of course we can use `# rubocop:disable`, but:
- for `get_min!`, it does not look like a genuine accessor, IMHO it should not fire at all
- for other the cases, it's just nicer to avoid cluttering the source with magic comments, but it's also less precise (it is project-wise), so I can see reason to reject this.

Thanks!

**Comment by Earlopain** [comment]
Personally I have used `fetch` in these cases. Maybe because of the constraints the cop imposes but I also feel like that communicates more clearly that the method is doing more than meets the eye. Not a native speaker though.

For `!`, docs https://docs.rubocop.org/rubocop/cops_naming.html#namingaccessormethodname already have a note about the expected arity and I don't think it would be that big of a stretch to expand that to bang methods since it also doesn't look like a tradition accessor. Though I also don't see the problem in just following the cop here.

**Comment by koic** [comment]
Names ending with `!` or `?` are not appropriate as attribute names, so it seems reasonable to allow them. I opened #13151. However, considering the role of this cop, I'm still uncertain about the appropriateness of having an allow list.

**Comment by akimd** [comment]
This is fine by me.  @Earlopain 's suggestion for fetch is nice, we will probably move to it.  Thanks to both of you.

**Comment by G-Rath** [comment]
@koic I've run into this in some API clients which use `get` since that's the underlying HTTP verb - while I do generally agree that `fetch` is a better name for conveying that the method has a higher cost than a "get property" kind of action, it's still possible that `get` is a better fit in some cases (including accounting for dev team preference), and this tends to poison the rest of the code e.g. not only do we have to disable this at the official method definition in the class, we have to do so in cases like mocks where we redeclare the method.

If you're happy to accept a pull request adding support for an allowlist, I'm happy to create a issue and do the work :)
