### ISSUE TITLE
Reconsider required commas for trailing comma cops for literals with braces on the same line

### ISSUE THREAD

**Issue by fatkodima** [rubocop/rubocop#13394]
When having
```yml
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
```

it produces an offense for 
```ruby
a = [1,
     2,
     3]
```
and requires to put a comma after `3` which is just annoying and does not give benefits (like smaller git diffs when adding a new item at the end).

I would suggest reconsider this rule for the comma to not be required for this case.

**Comment by koic** [comment]
The intent is understood, but this appears to align with the specification for `EnforcedStyleForMultiline: consistent_comma`. If that approach is not preferred, `EnforcedStyleForMultiline: comma` should be used instead.
https://docs.rubocop.org/rubocop/1.67/cops_style.html#styletrailingcommainarrayliteral

Since trailing commas are often a point of debate, the existing commitments for each option should be maintained, I think.
