### ISSUE TITLE
Bug in StringLiteralsInInterpolation

### ISSUE THREAD

**Issue by bquorning** [rubocop/rubocop#1415]
``` sh
$ cat foo.rb
"foo" \
  "bar"

$ bin/rubocop --only StringLiteralsInInterpolation -- foo.rb
Inspecting 1 file
C

Offenses:

foo.rb:1:1: C: Prefer single-quoted strings inside interpolations.
"foo" \
^^^^^
foo.rb:2:3: C: Prefer single-quoted strings inside interpolations.
  "bar"
  ^^^^^

1 file inspected, 2 offenses detected

$ bin/rubocop --version
0.27.0
```

Since there isn’t any interpolation into the given string, this looks like a bug.

**Comment by vinagrito** [comment]
Just wondering, what about:
`:"#{some_str.gsub('/', '_')}_some_other_string"` - Not working
while this:
`"#{some_str.gsub('/', '_')}_some_other_string".to_sym` - Does work

**Comment by jonas054** [comment]
@vinagrito Did you mean, why doesn't RuboCop report the single quotes in the first example if the preference is `double_quotes` for `StringLiteralsInInterpolation`? It's because that's a symbol literal. The second example is a string literal.

It looks like this cop, and some others that deal with interpolation, miss the symbol literal case.

**Comment by vinagrito** [comment]
@jonas054 gotcha
