### ISSUE TITLE
Inherit config from gems

### ISSUE THREAD

**Issue by lenntt** [rubocop/rubocop#290]
[Feature request]

Hi,

Rake tasks are pretty much the way to go in ruby. its great for having things run in a build.

Also, rake tasks can be distrubuted by gems/rails engines etc, to reduce code duplication per project.
E.g. it is now hard to share the config like that. I was thinking of something like:

```
Rubocop::Config::inherit_from(File.join(MyEngine::Engine.root, 'config/rubocop_checks.yml'))
```

(since you cant do this in .yml)

It would be great if there's an API to support this.

My current rake task that is used by my build task:

```
desc 'Verify code conventions'
task :rubocop do
  puts 'Rubocop checking application ...'
  system 'bundle exec rubocop --silent'
  fail if $?.exitstatus != 0
end
```

**Comment by jhansche** [comment]
I've also recently run into a situation where it would be helpful to inherit a rubocop config from a gem's library path.  I'm not saying it's up to Rubocop to install the gem, or determine the most up to date version, or anything like that;  but if the project is using a gem, then presumably that gem has already been installed, and presumably executing rubocop would be done from a context in which the gem is already accessible.

To simplify the implementation, it could be a new yml key (something like `inherit_from_gem`, which takes a Hash of `<gem_name>: <path_within_gem/rubocop.yml>`):

```yaml
inherit_from: .rubocop_todo.yml

inherit_from_gem:
  cucumber: 'config/rubocop.yml'
  my_shared_gem: 'path/to/my/rubocop.yml'

AllCops:
  # ...
```

And the config loader would essentially perform something like:

```ruby
def resolve_inheritance_from_gem(gem_name, relative_config_path)
  spec = Gem::Specification.find_by_name(gem_name)
  f = File.join(spec.gem_dir, relative_config_path)
  load_file(f)
end
```

If the gem isn't available, it could either be silently ignored, or a proper error could be emitted suggesting that the required gem needs to be installed (or suggesting `bundle install` if a `Gemfile` exists, for example).

I understand the argument that this may be orthogonal to Rubocop, but it's not like this is anything that requires particularly obscure Ruby -- most projects successfully make use of shared gems, and if a project wants to use a shared rubocop configuration (*without* the need to maintain any symlinks, submodules, or `~/.rubocop.yml` files), I don't see that as something that should be wildly avoided or discouraged.  Using the DEFAULT_FILE could even piggy back on this, such that the default rubocop file would be loaded using:

```ruby
resolve_inheritance_from_gem('rubocop', 'config/default.yml')
```

I don't mean to resurrect a 2-year-old issue that was closed, but really all the alternatives given do not lend themselves to a "works-out-of-the-box" project -- i.e., where a Jenkins CI job can easily invoke rubocop for the project with:

```shell
bundle install
bundle exec rubocop
```

In fact, I would consider all of the suggested alternatives above specifically *discouraged*, because they each require external tools (symlinks, which are not supported on all platforms; `git submodule` which is specific to the git SCM; a Rake task, which is specific to using rake at all, and many projects do not; or a shell script, which is also going to be platform-dependent in one way or another) to achieve the same end result, whereas allowing RuboCop to be gem-aware keeps all the behavior of loading a config from a gem path self-contained in the Ruby language -- the very language it is intended to work on.
