### ISSUE TITLE
Disable Performance/UnfreezeString in default config

### ISSUE THREAD

**Issue by bquorning** [rubocop/rubocop#4968]
Re. #4586

I’m a bit sad to see Performance/UnfreezeString being enabled by default.

Yes, the unary operator makes it possible to allocate mutable strings a bit faster, but isn’t the point of having frozen strings in Ruby 3 that we shouldn’t allocate very many mutable strings anyway?

I would argue that `String.new` is more readable than `+''`, and `String.new('foo')` is more readable than `+'foo'`. And since the string object returned by `String.new` is ASCII, I would advocate for calling it with a UTF-8 encoded argument, e.g. `String.new('')`.

If anything, we should push the Ruby core team to optimize `String.new` to *not* allocate a 2nd object when called with a string literal argument.

cc/ @pocke @koic

**Comment by bquorning** [comment]
Bump @pocke , @koic

**Comment by pocke** [comment]
Yes, in many cases, we can use `String.new` (or `String#dup`) instead of `String#+@`. Because in many cases it is not a bottleneck in an application. For example, DB queries are bottlenecks in a Rails application.
However, it may be a bottleneck in libraries or [the language](https://github.com/ruby/ruby). So, I think the cop should be enabled in libraries.
And I think the same is true of other performance cops.

So, I think we should separate performance cops to a gem like rubocop-performance. 
See https://github.com/bbatsov/rubocop/issues/5169

In a Rails application, we can ignore rubocop-performance. And in a library, we can enable performance checks with rubocop-performance.

> If anything, we should push the Ruby core team to optimize String.new to not allocate a 2nd object when called with a string literal argument.

I read k0kubun's blog article, and it is written in his article that it is difficult. Because `String.new` fetches `String` constant.

> また、.newのメソッド呼び出し以外にStringという定数の取得が走るため、定数取得の際インラインキャッシュは使われるものの微妙に遅い
> 
> https://qiita.com/k0kubun/items/1c3e605645ba5ff683a1 (It's written in Japanese.)
