### ISSUE TITLE
Rubocop finds .rubocop.yml in parent directories

### ISSUE THREAD

**Issue by b4hand** [rubocop/rubocop#536]
I have a project that vendors in another project using git submodules both of which I work inside. So my file system looks something like this:

```
src/
src/project1
src/project1/.rubocop.yml
src/project1/vendor
src/project1/vendor/project2
src/project1/vendor/project2/.rubocop.yml
```

Inside src/project1/.rubocop.yml I exclude the vendor directory using `vendor/**`. Unfortunately, this means that when I run rubocop from within project2 it picks up the Exclude and then rubocop says it is "Inspecting 0 files". This is not what I intended. I simply don't want to see rubocop issues for vendor when I'm building within project1, but I do want to see them when I'm building within project2. Here's some output from rubocop --debug:

```
For /home/brandon/src/mozlinks/vendor/askari: configuration from /home/brandon/src/mozlinks/vendor/askari/.rubocop.yml
Default configuration from /home/brandon/.rbenv/versions/jruby-1.7.4/lib/ruby/gems/shared/gems/rubocop-0.12.0/config/default.yml
Inheriting configuration from /home/brandon/.rbenv/versions/jruby-1.7.4/lib/ruby/gems/shared/gems/rubocop-0.12.0/config/enabled.yml
Inheriting configuration from /home/brandon/.rbenv/versions/jruby-1.7.4/lib/ruby/gems/shared/gems/rubocop-0.12.0/config/disabled.yml
AllCops/Excludes configuration from /home/brandon/src/mozlinks/.rubocop.yml
```

That last line is the issue. Is there a reason rubocop walks the directory tree up looking for configuration higher than my current invocation path even when it has already found a `.rubocop.yml`?

**Comment by agibralter** [comment]
I know this is super old... but it might be nice if it was configurable to stop the traversal through parent directories. I just had some confusing/surprising behavior because I accidentally had a .rubocop file in my home directory.

**Comment by jonas054** [comment]
@agibralter Your problem only occurs if you have no `.rubocop.yml` in the project where you're running `rubocop`, but there's one higher up, or in your home directory. You can get RuboCop to not look for any configuration file and just run with default configuration like this:
```
rubocop --force-default-config
```

**Comment by vStone** [comment]
using `rubocop -c .rubocop.yml` also does seem to prevent looking for other .rubocop.yml files in parent directories.

**Comment by Kache** [comment]
I just ran into this behavior, and also found it surprising that the first `.rubocop.yml` configuration found doesn't take full precedence.

> This has an unwanted implication that would have to be fixed.

@jonas054 can you elaborate? I don't understand your example why taking the first `.rubocop.yml` looking upwards would break expected behavior. (Isn't that how bundler works, btw?)

Are you saying that it's intended to have multiple nested `.rubocop.yml` files in a single project, e.g. one at `PROJ_ROOT/`, one in `PROJ_ROOT/lib`, so rubocop always searches up?

**Comment by jonas054** [comment]
> Are you saying that it's intended to have multiple nested .rubocop.yml files in a single project, e.g. one at PROJ_ROOT/, one in PROJ_ROOT/lib, so rubocop always searches up?

Yes, that is supported. I don't think that feature is used much, having multiple `.rubocop.yml` within a project, but the situation with vendor directories, as described at the top of this page, is probably common.

> I don't understand your example why taking the first .rubocop.yml looking upwards would break expected behavior.

Think of vendor directories, i.e. code from other projects being copied in to your project. If you say in your project that you don't want to inspect the files in vendor directories, the `.rubocop.yml` files in those directories should not be able to override your preference.

Note that it's only `Exclude` parameters that are taken from a higher level. Everything else comes from the nearest `.rubocop.yml`. Note also that since these comments were written, the command line option `--ignore-parent-exclusion` has been added.

**Comment by deivid-rodriguez** [comment]
@jonas054 Could you give me a practical example in which the current behaviour is expected?

Say I have a layout like the one mentioned originally

```
src/
src/project1
src/project1/.rubocop.yml
src/project1/vendor
src/project1/vendor/project2
src/project1/vendor/project2/.rubocop.yml
```

Whereas if you run rubocop from the projec1 root folder, you _do want_ your exclusions to be applied, if for some reason you _explicitly switch_ to the vendored project2 in order to run rubocop, I can't think of a reason why it shouldn't go ahead and inspect the files and disregard exclusions further up.

You mentioned https://github.com/rubocop-hq/rubocop/issues/288 as the original motivation for the current special handling of `AllCops/Exclude` but that I don't think removing the special handling would break exclusions like the ones in that issue.

For what it's worth, I created at PR that fixes this: https://github.com/rubocop-hq/rubocop/pull/8176.

**Comment by jonas054** [comment]
> I can't think of a reason why it shouldn't go ahead and inspect the files and disregard exclusions further up

From the perspective of running RuboCop on the command line, standing in different directories, you may have a point. But it would mean that we have to consider _current directory_ in the exclusion logic, and that logic is already pretty complex. Wouldn't it affect RuboCop editor integration if current directory is added as a factor in the inspection algorithm?

**Comment by deivid-rodriguez** [comment]
You're right, although I made some testing in #8176 when the initial approach was to use CWD, and results seemed either the same or superior. But I only checked my particular integration. Anyways, I dropped the CWD approach because that reason: it felt potentially breaking even if I couldn't figure out how.
