### ISSUE TITLE
Add flag to rescue and ignore infinite loop cases

### ISSUE THREAD

**Issue by nakulpathak3** [rubocop/rubocop#7349]
I'm trying to run rubocop safe autocorrect on a 5000 file project. I keep running into infinite loops after running about ~1300 of the files. I then exclude that file altogether and re-run safe autocorrect. 

It would be nice to have `--ignore-infinite-loops` flag for autocorrect and/or safe autocorrect for cases like mine. I expect such a flag to rescue the infinite redirect, simply leave the exception causing error/line and continue running. I can then regenerate my rubocop todo and leave things for manual intervention for when our team has more time.

While I understand that we should be trying to resolve all such errors, running into 20 different infinite loop detects and having to exclude 20 different files to get safe autocorrect to run on my whole project is quite frustrating. Until the day we can confidently say we no longer run into infinite redirects, this would be a good flag to have around.

**Comment by bbatsov** [comment]
Well, it's not like those loops are something intentional that we're tracking. I don't want to complicate cop logic with adding some tracking of how exactly the auto-correct is going and whether there are constant back and forths with other cops, which would be necessary to provide the option you suggest. I wonder if there are safer ways to achieve this.

**Comment by jonas054** [comment]
@nakulpathak3 Which cops are causing infinite loops? Fixing those bugs has to be priority one, so please open new issues unless it's already been reported.

Hiding the bugs might be important in your specific case, but from the RuboCop project's perspective it's not so important.
