### ISSUE TITLE
Better disable uncorrectable

### ISSUE THREAD

**Issue by marcandre** [rubocop/rubocop#8161]
Assuming a method already with a `rubocop:todo`, `rubocop -a --disable-uncorrectable` will not amend the comment and instead wrap the method with a `todo` and an `enable`.

It would be nice if instead it amended the existing todo.

Instead of:
```
+       # rubocop:todo Metrics/AbcSize
        def on_begin(node) # rubocop:todo Metrics/CyclomaticComplexity
          # ...
        end
+       # rubocop:enable Metrics/AbcSize
```

Getting:
```
-       def on_begin(node) # rubocop:todo Metrics/CyclomaticComplexity
+       def on_begin(node) # rubocop:todo Metrics/AbcSize, Metrics/CyclomaticComplexity
          # ...
        end
```

**Comment by marcandre** [comment]
Similarly, if the method is already wrapped, if it could amend the wrapping.

Instead of:
```
        # rubocop:todo Metrics/CyclomaticComplexity
+       # rubocop:todo Metrics/AbcSize
        def find_redundant(comment, offenses, cop, line_range, next_line_range)
          # ...
        end
+       # rubocop:enable Metrics/AbcSize
        # rubocop:enable Metrics/CyclomaticComplexity
```
Getting
```
-       # rubocop:todo Metrics/CyclomaticComplexity
+       # rubocop:todo Metrics/AbcSize, Metrics/CyclomaticComplexity
        def find_redundant(comment, offenses, cop, line_range, next_line_range)
          # ...
        end
-       # rubocop:enable Metrics/CyclomaticComplexity
+       # rubocop:enable Metrics/AbcSize, Metrics/CyclomaticComplexity
```

**Comment by rrosenblum** [comment]
I actually got started on this change a couple of weeks ago when looking into another issue with `--disable-uncorrectable`. I was only able to get this to partially work. I was hoping that the changes that @marcandre is working on for updating the autocorrect api would help with this. 

I can share the code that I have thus far. The problem that I was running into is that within the context that we are in for determining whether to auto-correct or disable, we seem to only have access to the original version of the file. If a comment disable already exists before we get to auto-correct/disable, then we can easily amend the existing comment. The problem is that we determine how to disable before modifications to the file happen so the second disable doesn't know that we already created a disable comment for the first one.

I also think there are some improvements that can be made to `Style/DoubleCopDisableDirective`. Currently, the cop will throw away extra comment disables. This doesn't seem like the appropriate intention behind what is going on. I would have expected the cop to merge disable comments rather than throwing away extra one.

**Comment by marcandre** [comment]
> I was hoping that the changes that @marcandre is working on for updating the autocorrect api would help with this.

I don't believe my branch will help, I've kept that processing the same. All cops run with uncorrected code (at first), then are re-run as long as there are corections. After all that then there's a very last run with `Cop::Lint::RedundantCopDisableDirective`; I must admit I wasn't super satisfied with that. I would be glad to find a better way to schedule ordre-dependent cops.
I wish I knew better the disabling/enabling cops to "see" what's the underlying concept. Would a cop setting like "I wanna make my corrections after such-and-such a cop / all-order-independent-cops (so discard my corrections if these guys make any)" help?

**Comment by marcandre** [comment]
@rrosenblum Another possible avenue would be to improve the API that tells us which lines are enabled/disabled for which cops so that it accepts updates. That API would be always up to date and could be the sole authority to issue the enabling/disabling corrections at the end.

**Comment by rrosenblum** [comment]
I'm sure there are some solutions that we can come up with. I was hesitant to begin making any real changes around auto-correct since such a large portion of the code is in the process of being refactored.

> Another possible avenue would be to improve the API that tells us which lines are enabled/disabled for which cops so that it accepts updates

This seems like a good idea. I'm not entirely sure how we would handle it at the moment. We'd need to build a collection for all the existing disables in the code. During auto-disable, we'd have to reference/update the list when we decide to disable.

I think I ran into some other potentially weird issues with variable scope in this area of the code. It's been a couple of weeks since I messed with it so I can't quite remember everything. I think it had something to do with how auto-correction is handled inside of cop so at the moment, we don't necessarily have a shared memory space for multiple cops to reference. The instance variables `@corrected_nodes` or `@corrections` would work similar to a disable registry, but it isn't shared across cops.

**Comment by thearjunmdas** [comment]
@marcandre  - This also looks fixed for me.

Original Code:
```ruby
def on_begin(node) # rubocop:todo Metrics/CyclomaticComplexity
  if node[:a]
    puts 'a'
  elsif node[:b]
    if node[:c]
      puts 'c'
    elsif node[:e]
      if node[:d]
        puts 'd'
        node[:e].times.each do |el|
          puts el
          puts 'something else'
          puts 'tada' if el
        end
      end
    end
  end
end
```

After **rubocop -a --disable-uncorrectable**:

```ruby
# rubocop:todo Metrics/PerceivedComplexity
# rubocop:todo Metrics/MethodLength
def on_begin(node) # rubocop:todo Metrics/CyclomaticComplexity
  if node[:a]
    puts 'a'
  elsif node[:b]
    if node[:c]
      puts 'c'
    elsif node[:e]
      if node[:d]
        puts 'd'
        node[:e].times.each do |el|
          puts el
          puts 'something else'
          puts 'tada' if el # rubocop:todo Metrics/BlockNesting
        end
      end
    end
  end
end
# rubocop:enable Metrics/MethodLength
# rubocop:enable Metrics/PerceivedComplexity
```

**Comment by marcandre** [comment]
I think that ideally, the output would merge the outer comments:

> ```ruby
> # rubocop:todo Metrics/MethodLength, Metrics/PerceivedComplexity
> def on_begin # ...
> end
> # rubocop:enable Metrics/MethodLength,  Metrics/PerceivedComplexity
> ```

**Comment by jamesbebbington** [comment]
Did https://github.com/thearjunmdas/rubocop/commit/8d3a96a96521703d8d769510b0268d2cd2372127 perhaps also fix this particular issue?

**Comment by marcandre** [comment]
Yeah, I think so, thanks!
