### ISSUE TITLE
New cop: `Style/DataClass`

### ISSUE THREAD

**Issue by fatkodima** [rubocop/rubocop#8494]
This was inspired by https://rubystyle.guide/#struct-new

But that looks a bit misleading to me. It's obvious that it suggests changing classes with only constructor and attribute accessors to `Struct.new`, but I'm not sure if it suggests so when class has other members, like this
```ruby
class Person
  attr_accessor :first_name, :last_name

  def initialize(first_name, last_name)
    @first_name = first_name
    @last_name = last_name
  end

  def some_method
    # ... something
  end
end
```

into this

```ruby
Person = Struct.new(:first_name, :last_name) do
  def some_method
    # ... something
  end
end
```
?

I'm proposing a cop, that suggest to translate dumb classes (only with constructor and accessors), with probably configured min number of accessors to have to get a violation, into `Struct.new`. 
Real-life example of violation: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/git/blame.rb#L61-69

**Comment by marcandre** [comment]
Interesting suggestion.

I like using `Struct`, but I'm always frustrated when I do so because of some errors in design that probably can't be addressed.

The main reason I want to use it, is to avoid writing that `initialize` method. But the `initialize` method generated has very strict limitations: no default values, no keyword parameters or else it's all keyword parameters, again with no defaults. I also think that the existing of `Struct#to_a` was a design error. One example is `Array(my_struct_instance)`... I dislike `Struct#members` too. Finally, I'm leaning a lot towards immutable structures and prefer `attr_reader` to `attr_accessor`. It's not clear in your example if it is intentional that it's `attr_accessor`.

All that to say: could be useful to some, but definitely would be a `Safe: false`, `Enabled: false` cop imo.

**Comment by fatkodima** [comment]
> All that to say: could be useful to some, but definitely would be a Safe: false, Enabled: false cop imo.

Yeah, it would be useful to me, as I prefer and it is more explicit to me when using `Struct.new` that this is dumb only data-like class.

**Comment by fatkodima** [comment]
Changed my mind regarding this style.
