### ISSUE TITLE
--regenerate-todo should regenerate the todo only for  the files passed as argument

### ISSUE THREAD

**Issue by dgmora** [rubocop/rubocop#9711]
## Is your feature request related to a problem? 

Not sure if it's a bug or a feature, I have looked on how to do this but didn't find a way at least. 
`bundle exec rubocop --regenerate-todo my_file.rb` lints only `my_file.rb` but regenerates the whole todo file (thus deleting everything in the todo file).

## Describe the solution you'd like

I would expect that if I pass some files to rubocop, the todo is only regenerated for those files. This would help in an iterative approach were you improve the code base file by file. So every time you touch a file, you improve it and the todo gets correctly updating without having to run it for the whole code base. 

## Describe alternatives you've considered

I have not found a way to do this. The only way to do this is to rerun rubocop --regenerate-todo for the whole code base, but this is slow.

**Comment by jonas054** [comment]
Basically it's not possible to regenerate the todo file just for a set of updated source code files. The reason is that RuboCop doesn't know which parts of the todo file are related to which source files. Except for `Exclude` properties where it's apparent which files the offeses were in. But in general it's not possible.

**Comment by dgmora** [comment]
While it'd be nice that this works, that makes sense!
