### ISSUE TITLE
Request: Lint/SafeNavigationConsistency short-circuit option for &&

### ISSUE THREAD

**Issue by johnnyshields** [rubocop/rubocop#9816]
When using `Lint/SafeNavigationConsistency` in an `&&` / `and` experission, I'd like if `variable&.` is only required the first time that variable is used. In terms of boolean logic, any subsequent usages of `variable&.` are redundant because `&&` are short-circuit evaluated.

(Note that for `||` / `or` and other operators it is still needed on each instance of that variable)

I would suggest to make this an option such as `ShortCircuitAndOperator`

**Lint/SafeNavigationConsistency - Desired behavior**

```ruby
@foo&.bar? && @foo.baz?
```

**Lint/SafeNavigationConsistency - Currently enforced behavior**

```ruby
@foo&.bar? && @foo&.baz?
```

#### RuboCop version

```
bundle exec rubocop -V
1.15.0 (using Parser 3.0.1.1, rubocop-ast 1.5.0, running on ruby 2.6.6 x64-mingw32)
  - rubocop-rails 2.10.1
```

**Comment by AndreiEres** [comment]
Make sense. But I prefer that behaviour: `@foo&.bar? && @foo&.baz?`. It save us when we remove or replace first part with something else.

**Comment by johnnyshields** [comment]
If you change it, Rubocop will catch the change 😄 (assuming you're running it on CI)

Anyway, I'm asking for this to be an optional config; it's fine if it's not the default.

**Comment by jonas054** [comment]
@rrosenblum You added this cop. Do you have an opinion?

**Comment by rrosenblum** [comment]
This feels like a departure from the intention of the cop itself. The cop is designed to ensure safe navigation consistency across conditions. It is designed to more explicitly show off that `nil` safety is needed for subsequent method calls. It's mainly helpful for preventing refactor errors that could arise from forgetting to add safe navigation to the second call if the first call is ever removed. If `@foo&.bar? && @foo.baz?` ever becomes `@foo.baz?` then `nil` safety is lost. It is up to the developer to maintain safety across the refactor.

Maintaining `@foo&.bar? && @foo.baz?` can be achieved by disabling the cop. There isn't a configuration that allows converting `@foo&.bar? && @foo&.baz?` to `@foo&.bar? && @foo.baz?`. I think it could be reasonable to support a config option for this style since we tend support a lot of opposite formatting.

I think the existing configuration should be left as is by default since it produces the safest code.

**Comment by rrosenblum** [comment]
I started working on this feature a little while ago. It's a bit more complicated to implement than I initially thought it would be. I may have to change the reporting of offenses to be a single offense for multiple issues rather than multiple offenses in order to maintain auto-correct. Without auto-correct, multiple offenses are. There is an edge case with non-dot methods where auto-correct would be harmful to the meaning of the code. I also haven't had as much free time to work on this as I initially thought I would. I'm still working on it, it just might take a little while

**Comment by johnnyshields** [comment]
@rrosenblum thank you, really appreciate it! Will definitely enable when you have it.

**Comment by mathieujobin** [comment]
Came here for exactly this, I wish this gets implemented.

**Comment by akimd** [comment]
Likewise.

FWIW, this statement is not very convincing to me:

> If `@foo&.bar? && @foo.baz?` ever becomes `@foo.baz?` then nil safety is lost. It is up to the developer to maintain safety across the refactor.

When you change code, well, changes might be needed.  YAGNI.  Let's not write things for a future that might not exist.

On the other hand, reading `@foo&.bar? && @foo.baz?` is surprising, and I think that code should be as little surprising as possible.  So here (to _my_ eyes), in this precise situation, the cop is pushing towards less readable code.

**Comment by rrosenblum** [comment]
@akimd you bring up some good points. The safe navigation cops were written early on when safe navigation was first added to Ruby. We chose to adhere to a safe default. Standards should evolve over time. Anyone is welcome to submit a Pull Request with the changes. This has admittedly gotten away from me.

If I remember correctly, I had the desired config functioning in my Pull Request. I had identified some limitations of the existing cop and an enhancement to the way the cop is implemented. This had been flagged as no rush, however several years kinds of exceeds that in my mind.

Maybe it is time to separate the config change from the further enhancements of the cop.

**Comment by koic** [comment]
Since this cop is categorized as Lint rather than Style, it should strictly adhere to the language specifications without any excess or deficiency in behavior. As a basic behavior, in the case of `&&`, if the first receiver is `nil`, the subsequent condition is not evaluated, so the safe navigation is unnecessary for the following receiver. On the other hand, with `||`, if safe navigation is used for the first receiver, it is required for the subsequent receiver. In both cases, if safe navigation is not used on the receiver in the initial condition, it is unnecessary for the following conditions as well. Taking these factors into account, I will proceed with a comprehensive revision while maintaining the currently released configuration options.
